service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: main.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 30
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
    environment: ${file(./dev.env.json)}

configValidationMode: warn
