
name: CD workflow

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up Node 
        uses: actions/setup-node@v1
        with:
        node-version: 14

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        name: Serverless Deploy
        uses: dhollerbach/github-action-serverless-with-python-requirements@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_QA }}

